version: "3"
services: 
  # db:
  #   image: "postgres:latest"
  #    volumes:
  #     - ./my_data_directory:/var/lib/postgresql/data
  # networks:
  #   - my_network
  # environment:
  #   POSTGRES_PASSWORD: 
  #   POSTGRES_USER:
  #   POSTGRES_DB: 

  server:
    build: ./api
    ports:
      - "8080:8080"
    # networks:
    #   - my_network
    # depends_on:
    #   - db

  frontend:
    build: ./ui/docker-practice
    ports:
      - "3000:3000"
    # networks:
    #   - my_network
    depends_on:
      - server

# networks:
#   my_network:
#     driver: bridge